### ISSUE TITLE
Lack of QnAs for the Finesse Benchmark tool

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/finesse-data#7]
## Summary
The finesse benchmark tool is functional and starting to produce accuracy scores on the QnA, but there are too few question samples to test. We would like to increase the number of questions to 100 to obtain more meaningful and reliable results.

## Tasks
- [ ] Increase the number of question samples to 100 for testing accuracy.

## Acceptance Criteria 
- Ensure the finesse benchmark tool can handle 100 question samples without performance issues.
- Validate that the accuracy scores generated by the tool are consistent and meaningful with the increased sample size.
- Confirm that the results obtained with 100 questions provide reliable insights into the performance and accuracy of Finesse.

**Comment by JolanThomassin** [comment]
# 100 QnA generated

- 100 : 21
- 100 : 12
- 100 : 19
- 100 : 21
- 100 : 13
- 100 : 14
- 600 : 86

---

Out of 600 chunks selected, only 100 questions were returned. The remaining 500 were deleted because they were deemed unusable and contained one of the following words:

```python
words_to_check = [
    "This page is part",
    "Cette page fait partie",
    "Archivée",
    "archivée",
    "Archived",
    "archived",
]
