### ISSUE TITLE
Investigate low score issue for to_sort_2024_02_22 of Azure Engine

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/finesse-data#9]
## Summary
One third of the questions in `to_sort_2024_02_22` have a score of 0%. This is entirely normal because the AI question generation script does not always generate relevant questions. That's why it's crucial to separate vague (bad) questions from relevant (good) ones.

## Tasks
- [x] Sort duplicate, vague, web page not found questions
- [x] #11

**Comment by ibrahim-kabir** [comment]
> @ibrahim-kabir incomplete checklist? are there follow up to be done?

Thank you for notifying. I have removed an irrelevant issue from the investigation. This issue will be reopened as the final step is yet to be investigated.

**Comment by rngadam** [comment]
watch out for spelling of Investigate
